yonhjoon/STAEZ

staez/src/main/java/com/spring/staez/admin/controller/AdminController.java
staez/src/main/java/com/spring/staez/admin/model/dao/AdminDao.java
staez/src/main/java/com/spring/staez/admin/service/AdminService.java
staez/src/main/java/com/spring/staez/common/controller/CommonController.java
staez/src/main/java/com/spring/staez/common/model/dao/CommonDao.java
staez/src/main/java/com/spring/staez/common/service/CommonService.java
staez/src/main/java/com/spring/staez/community/controller/CommunityController.java
staez/src/main/java/com/spring/staez/community/model/dao/CommunityDao.java
staez/src/main/java/com/spring/staez/community/service/CommunityService.java
staez/src/main/java/com/spring/staez/concert/controller/ConcertController.java
staez/src/main/java/com/spring/staez/concert/model/dao/ConcertDao.java
staez/src/main/java/com/spring/staez/concert/service/ConcertService.java
staez/src/main/java/com/spring/staez/inquire/controller/InquireController.java
staez/src/main/java/com/spring/staez/inquire/model/dao/InquireDao.java
staez/src/main/java/com/spring/staez/inquire/service/InquireService.java
staez/src/main/java/com/spring/staez/mypage/controller/MypageController.java
staez/src/main/java/com/spring/staez/mypage/model/dao/MypageDao.java
staez/src/main/java/com/spring/staez/mypage/service/MypageService.java
staez/src/main/java/com/spring/staez/others/controller/OthersController.java
staez/src/main/java/com/spring/staez/others/model/dao/OthersDao.java
staez/src/main/java/com/spring/staez/others/service/OthersService.java
staez/src/main/java/com/spring/staez/user/controller/UserController.java
staez/src/main/java/com/spring/staez/user/model/dao/UserDao.java
staez/src/main/java/com/spring/staez/user/service/UserService.java
staez/src/main/webapp/WEB-INF/views/common/header.jsp
staez/src/main/webapp/WEB-INF/views/community/communityMain.jsp
staez/src/main/webapp/resources/css/community/communityMain.css

-[O] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[] 의존성, 환경 변수, 빌드 관련 코드 업데이트
컨트롤러 및 백엔드 패키지 구조 제작하였습니다.
아래 방식으로 외부 css, 이미지 등을 가져옵니다.
```html
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
...
<link rel="stylesheet" href="<c:url value='/resources/css/community/communityMain.css'/>">
```

[주재완] 2024.05.17 개발 내역

---

staez/src/main/java/com/spring/staez/user/model/vo/User.java

[장용준] fix User.java 출동수정 (ㅠㅠ)

---

staez/src/main/java/com/spring/staez/user/controller/UserController.java
staez/src/main/webapp/WEB-INF/views/user/findIdForm.jsp
staez/src/main/webapp/WEB-INF/views/user/findPwdForm.jsp
staez/src/main/webapp/WEB-INF/views/user/idListForm.jsp
staez/src/main/webapp/WEB-INF/views/user/newPwdForm.jsp
staez/src/main/webapp/resources/css/user/findId.css
staez/src/main/webapp/resources/css/user/findPwd.css
staez/src/main/webapp/resources/css/user/idListForm.css

[장용준] Feat : 아이디찾기 UI 완성
비밀번호 찾기 UI 완성
비밀번호 변경 UI 완성

[장용준] Feat : 아이디찾기 UI 완성

---

staez/src/main/webapp/WEB-INF/views/user/findIdForm.jsp
staez/src/main/webapp/WEB-INF/views/user/findPwdForm.jsp
staez/src/main/webapp/WEB-INF/views/user/idListForm.jsp
staez/src/main/webapp/WEB-INF/views/user/loginForm.jsp
staez/src/main/webapp/WEB-INF/views/user/newPwdForm.jsp
staez/src/main/webapp/WEB-INF/views/user/signinForm.jsp
staez/src/main/webapp/resources/css/user/findId.css
staez/src/main/webapp/resources/css/user/findPwd.css
staez/src/main/webapp/resources/css/user/login.css
staez/src/main/webapp/resources/css/user/signin.css

닉네임 아이디 중복검사 script
이메일 접미사가 변경될 때마다 호출
번호로찾기 이메일로찾기 block none 스크립트
본인명의로된 아이디 list
전체UI부분 수정

[장용준] Feat : 모든 버튼 링크 이동

---

staez/src/main/java/com/spring/staez/admin/controller/AdminController.java
staez/src/main/java/com/spring/staez/community/controller/CommunityController.java
staez/src/main/java/com/spring/staez/concert/controller/ConcertController.java
staez/src/main/java/com/spring/staez/concert/controller/ConcertReserveController.java
staez/src/main/java/com/spring/staez/inquire/controller/InquireController.java
staez/src/main/java/com/spring/staez/others/controller/OthersController.java

admin, community, concert, concertReserve, inquire, others  url 정하기

[주재완] URL 수정 참고 사항

---

staez/src/main/webapp/WEB-INF/views/admin/adminHeader.jsp
staez/src/main/webapp/WEB-INF/views/admin/communityMain.jsp
staez/src/main/webapp/WEB-INF/views/admin/concertMain.jsp
staez/src/main/webapp/WEB-INF/views/admin/faqMain.jsp
staez/src/main/webapp/WEB-INF/views/admin/inquireMain.jsp
staez/src/main/webapp/WEB-INF/views/admin/noticeMain.jsp
staez/src/main/webapp/WEB-INF/views/admin/reportIncertForm.jsp
staez/src/main/webapp/WEB-INF/views/admin/reportMain.jsp
staez/src/main/webapp/WEB-INF/views/admin/theaterMain.jsp
staez/src/main/webapp/WEB-INF/views/common/header.jsp
staez/src/main/webapp/WEB-INF/views/community/communityDetail.jsp
staez/src/main/webapp/WEB-INF/views/community/communityMain.jsp
staez/src/main/webapp/resources/css/admin/notice.css
staez/src/main/webapp/resources/css/main.css

[주재완] Fix : url 변경 사항 수정, css 수정

---

staez/src/main/webapp/WEB-INF/views/user/findIdForm.jsp
staez/src/main/webapp/WEB-INF/views/user/findPwdForm.jsp
staez/src/main/webapp/WEB-INF/views/user/idListForm.jsp
staez/src/main/webapp/WEB-INF/views/user/insertForm.jsp
staez/src/main/webapp/WEB-INF/views/user/insertPwdForm.jsp
staez/src/main/webapp/WEB-INF/views/user/loginForm.jsp
staez/src/main/webapp/resources/js/user/findIdForm.js
staez/src/main/webapp/resources/js/user/findPwdForm.js
staez/src/main/webapp/resources/js/user/idListForm.js
staez/src/main/webapp/resources/js/user/inserForm.js
staez/src/main/webapp/resources/js/user/insertPwdForm.js
staez/src/main/webapp/resources/js/user/loginForm.js

insertPwdForm파일 이름을 바꿈
모든파일 js파일만들고 옮김

[장용준] Rename : newPwdForm 파일이름을

---

staez/src/main/java/com/spring/staez/user/controller/UserController.java
staez/src/main/java/com/spring/staez/user/model/dao/UserDao.java
staez/src/main/java/com/spring/staez/user/service/UserService.java
staez/src/main/java/com/spring/staez/user/service/UserServiceImpl.java
staez/src/main/resources/mappers/user-mapper.xml
staez/src/main/webapp/WEB-INF/views/user/insertForm.jsp
staez/src/main/webapp/resources/css/user/insertForm.css
staez/src/main/webapp/resources/js/user/insertForm.js

[장용준] Feat : 택3중 3개만고르게 만듬 그리고 고른거 색상변하게 만듬

---

.gitignore
staez/src/main/webapp/.vscode/settings.json

- [] 기능 추가
- [] 기능 삭제
- [O] 버그 수정
- [] 의존성, 환경 변수, 빌드 관련 코드 업데이트
Joo -> main
- vscode 관련  ignore 처리

[주재완] 2024-05-22 수정사항

---

staez/src/main/java/com/spring/staez/user/controller/UserController.java
staez/src/main/java/com/spring/staez/user/model/dao/UserDao.java
staez/src/main/java/com/spring/staez/user/service/UserService.java
staez/src/main/java/com/spring/staez/user/service/UserServiceImpl.java
staez/src/main/resources/mappers/user-mapper.xml
staez/src/main/webapp/WEB-INF/views/user/findIdForm.jsp
staez/src/main/webapp/WEB-INF/views/user/findPwdForm.jsp
staez/src/main/webapp/WEB-INF/views/user/insertForm.jsp
staez/src/main/webapp/WEB-INF/views/user/loginForm.jsp
staez/src/main/webapp/resources/css/user/insertForm.css
staez/src/main/webapp/resources/js/user/insertForm.js
staez/src/main/webapp/resources/js/user/loginForm.js

[장용준] Feat : 중복확인 데이터 받아서 띄우기 만듬

---

staez/src/main/webapp/WEB-INF/views/user/insertForm.jsp
staez/src/main/webapp/resources/css/user/insertForm.css
staez/src/main/webapp/resources/js/user/insertForm.js

[장용준] Feat : 회원가입 js 완성 (중복체크 / 핸드폰 11자리 / 이메일/ 생년월이 0000-00-00)

[장용준] Feat : 회원가입 js 완성 (중복체크 / 핸드폰 11자리 / 이메일/ 생년월이 0000-00-00)

---

staez/src/main/webapp/WEB-INF/views/concert/concertMain.jsp
staez/src/main/webapp/resources/css/concert/concertMainView.css
staez/src/main/webapp/resources/js/concert/concertMain.js

[주재완] Design: communityMain 수정사항 반영 (slick 참고 커밋)

[주재완] Design: communityMain 수정사항 반영 (slick 참고 커밋)

---

staez/src/main/java/com/spring/staez/admin/controller/AdminController.java
staez/src/main/java/com/spring/staez/admin/model/dao/AdminDao.java
staez/src/main/java/com/spring/staez/admin/model/vo/Faq.java
staez/src/main/java/com/spring/staez/admin/service/AdminService.java
staez/src/main/java/com/spring/staez/admin/service/AdminServiceImpl.java
staez/src/main/java/com/spring/staez/user/model/vo/User.java
staez/src/main/resources/mappers/admin-mapper.xml
staez/src/main/webapp/WEB-INF/views/admin/faqIncertForm.jsp
staez/src/main/webapp/resources/js/admin/faqIncertForm.js

- [O] 기능 추가
- [] 기능 삭제
- [] 버그 수정
- [] 의존성, 환경 변수, 빌드 관련 코드 업데이트
Joo -> main
- 문의 사항 백엔드

[주재완] 2024.05.22 개발 사항

---

staez/src/main/resources/mappers/inquire-mapper.xml
staez/src/main/webapp/resources/js/inquire/inquireFAQ.js

[김효영] : 죄송해요

---

staez/src/main/java/com/spring/staez/concert/controller/ConcertController.java

[김남주] Feat: concertController 수정

---

staez/src/main/java/com/spring/staez/community/model/vo/Board.java
staez/src/main/java/com/spring/staez/inquire/controller/InquireController.java
staez/src/main/java/com/spring/staez/inquire/model/dao/InquireDao.java
staez/src/main/java/com/spring/staez/inquire/service/InquireService.java
staez/src/main/java/com/spring/staez/inquire/service/InquireServiceImpl.java
staez/src/main/resources/mappers/inquire-mapper.xml
staez/src/main/webapp/WEB-INF/views/inquire/inquireFAQ.jsp
staez/src/main/webapp/WEB-INF/views/inquire/inquireInsertForm.jsp
staez/src/main/webapp/resources/css/inquire/inquireFAQ.css
staez/src/main/webapp/resources/js/api/inquireapi.js
staez/src/main/webapp/resources/js/inquire/inquireFAQ.js
staez/src/main/webapp/resources/js/inquire/inquireInsertForm.js

[김효영] feat : 고객센터 얼추 끝

---

staez/src/main/java/com/spring/staez/admin/controller/AdminController.java
staez/src/main/java/com/spring/staez/admin/model/dao/AdminDao.java
staez/src/main/java/com/spring/staez/admin/service/AdminService.java
staez/src/main/java/com/spring/staez/admin/service/AdminServiceImpl.java
staez/src/main/java/com/spring/staez/concert/model/vo/Concert.java
staez/src/main/resources/mappers/admin-mapper.xml
staez/src/main/webapp/WEB-INF/views/admin/concertIncertForm.jsp
staez/src/main/webapp/resources/css/admin/concertInsertForm.css
staez/src/main/webapp/resources/js/admin/concertInsertForm.js
staez/src/main/webapp/resources/js/api/adminapi.js

[주재완] 2024-05-25 ~ 2024-05-26 작업분

---

staez/src/main/java/com/spring/staez/concert/controller/ConcertController.java
staez/src/main/java/com/spring/staez/concert/model/dao/ConcertDao.java
staez/src/main/java/com/spring/staez/concert/service/ConcertService.java
staez/src/main/java/com/spring/staez/concert/service/ConcertServiceImpl.java
staez/src/main/resources/mappers/concert-mapper.xml
staez/src/main/webapp/resources/js/api/concertapi.js
staez/src/main/webapp/resources/js/concert/concertDetail.js

[김남주] Feat: concertDetail 좋아요 구현중

[김남주] Feat: concertDetail 좋아요 구현중

---

staez/src/main/java/com/spring/staez/user/controller/UserController.java
staez/src/main/java/com/spring/staez/user/model/dao/UserDao.java
staez/src/main/java/com/spring/staez/user/service/UserService.java
staez/src/main/java/com/spring/staez/user/service/UserServiceImpl.java
staez/src/main/webapp/WEB-INF/views/user/insertForm.jsp
staez/src/main/webapp/resources/css/user/insertForm.css
staez/src/main/webapp/resources/js/api/userapi.js
staez/src/main/webapp/resources/js/user/insertForm.js

[장용준] Feat : 이메일 UUID 완성

---

staez/src/main/java/com/spring/staez/common/intercepter/LoginIntercepter.java
staez/src/main/java/com/spring/staez/community/controller/CommunityController.java
staez/src/main/java/com/spring/staez/community/model/dao/CommunityDao.java
staez/src/main/java/com/spring/staez/community/model/dto/AjaxBoardDto.java
staez/src/main/java/com/spring/staez/community/service/CommunityService.java
staez/src/main/java/com/spring/staez/community/service/CommunityServiceImpl.java
staez/src/main/resources/mappers/community-mapper.xml
staez/src/main/webapp/WEB-INF/views/community/communityDetail.jsp
staez/src/main/webapp/WEB-INF/views/community/communityMain.jsp
staez/src/main/webapp/resources/js/admin/theaterIncertForm.js
staez/src/main/webapp/resources/js/api/communityapi.js
staez/src/main/webapp/resources/js/common.js
staez/src/main/webapp/resources/js/community/communityDetail.js

Refactor : 공연 행을 반환하는 26진법 함수 common으로 이동
Feat: 커뮤니티 상세 페이지 ajax 관련(카테고리, 댓글 갯수, 좋아요 갯수)

[주재완] 2024-05-30 일부 개발 사항

---

staez/src/main/java/com/spring/staez/user/service/UserServiceImpl.java

[장용준] Fix: 이메일 인증 암호키 확인 오류메세지 안뜨는거 버그 해결

[장용준] Fix: 이메일 인증 암호키 확인 오류메세지 안뜨는거 버그 해결

---

staez/src/main/java/com/spring/staez/inquire/controller/InquireController.java
staez/src/main/java/com/spring/staez/inquire/model/dao/InquireDao.java
staez/src/main/java/com/spring/staez/inquire/service/InquireService.java
staez/src/main/java/com/spring/staez/inquire/service/InquireServiceImpl.java
staez/src/main/resources/mappers/inquire-mapper.xml
staez/src/main/resources/mappers/others-mapper.xml
staez/src/main/webapp/WEB-INF/views/inquire/inquireFAQ.jsp
staez/src/main/webapp/resources/css/others/concertCalendar.css
staez/src/main/webapp/resources/js/api/inquireapi.js
staez/src/main/webapp/resources/js/api/othersapi.js
staez/src/main/webapp/resources/js/inquire/inquireFAQ.js
staez/src/main/webapp/resources/js/others/concertCalendar.js
staez/src/main/webapp/resources/js/others/reservationCalendar.js

[김효영] feat  : 캘린더수정랑 고객센터 페이징처리 끝 아마도

[김효영] feat  : 캘린더수정랑 고객센터 페이징처리 끝 아마도

---

staez/src/main/java/com/spring/staez/concert/controller/ConcertController.java
staez/src/main/java/com/spring/staez/concert/model/dao/ConcertDao.java
staez/src/main/java/com/spring/staez/concert/service/ConcertService.java
staez/src/main/java/com/spring/staez/concert/service/ConcertServiceImpl.java
staez/src/main/resources/mappers/concert-mapper.xml
staez/src/main/webapp/WEB-INF/views/concert/concertDetailMain.jsp
staez/src/main/webapp/resources/js/api/concertapi.js
staez/src/main/webapp/resources/js/concert/concertDetailMain.js
staez/src/main/webapp/resources/js/concert/concertMain.js

[김남주] Feat: 콘서트 매퍼 수정

---

staez/src/main/java/com/spring/staez/concert/controller/ConcertReserveController.java
staez/src/main/java/com/spring/staez/concert/model/dao/ConcertReserveDao.java
staez/src/main/java/com/spring/staez/concert/service/ConcertReserveService.java
staez/src/main/java/com/spring/staez/concert/service/ConcertReserveServiceImpl.java
staez/src/main/resources/mappers/concertReserve-mapper.xml
staez/src/main/resources/mybatis-config.xml
staez/src/main/webapp/WEB-INF/views/concert/concertReserveStepOne.jsp
staez/src/main/webapp/resources/js/api/concertReserveapi.js
staez/src/main/webapp/resources/js/concert/concertReserveStepOne.js

[김효영] feat : concertReserve 서비스, 서비스임플, 다오, 맵퍼 , 마이파티스컴피그에 타입에리아스 추가

[김효영] feat : concertReserve 서비스, 서비스임플, 다오, 맵퍼 , 마이파티스컴피그에 타입에리아스 추가

---

staez/src/main/webapp/resources/js/concert/concertDetailMain.js

[김남주] Fix: 예매하기 코드 수정

---

staez/src/main/java/com/spring/staez/user/controller/UserController.java
staez/src/main/java/com/spring/staez/user/model/dao/UserDao.java
staez/src/main/java/com/spring/staez/user/model/vo/User.java
staez/src/main/java/com/spring/staez/user/service/UserService.java
staez/src/main/java/com/spring/staez/user/service/UserServiceImpl.java
staez/src/main/resources/mappers/user-mapper.xml
staez/src/main/webapp/WEB-INF/views/user/findIdForm.jsp
staez/src/main/webapp/WEB-INF/views/user/findPwdForm.jsp
staez/src/main/webapp/WEB-INF/views/user/insertForm.jsp
staez/src/main/webapp/resources/css/user/findPwd.css
staez/src/main/webapp/resources/js/user/findIdForm.js
staez/src/main/webapp/resources/js/user/findPwdForm.js

[장용준] Feat : user_mapper.xml에 user_name추가 및 회원가입 / 아이디찾기 / 비밀번호찾기 에 실명입력칸 추가
전부 select조건에 user_name추가함

[장용준] Feat : user_name추가

---

staez/src/main/java/com/spring/staez/concert/model/vo/Concert.java

[김남주] Fix : concert vo에 @SerializedName 삭제

[김남주] Fix : concert vo에 @SerializedName 삭제

---

staez/src/main/java/com/spring/staez/concert/controller/ConcertController.java
staez/src/main/java/com/spring/staez/concert/model/dto/ConcertDTO.java
staez/src/main/java/com/spring/staez/concert/service/ConcertRestTemplate.java
staez/src/main/java/com/spring/staez/concert/service/ConcertServiceImpl.java
staez/src/main/resources/mappers/concert-mapper.xml
staez/src/main/webapp/WEB-INF/views/concert/concertDetailMain.jsp
staez/src/main/webapp/WEB-INF/views/concert/concertMain.jsp

[김남주] Feat: 콘서트 api db 넣기 오류 수정중

[김남주] Feat: 콘서트 api db 넣기 오류 수정중

---

staez/src/main/java/com/spring/staez/common/template/AppInitializer.java
staez/src/main/java/com/spring/staez/concert/controller/ConcertController.java
staez/src/main/java/com/spring/staez/concert/model/dao/ConcertDao.java
staez/src/main/java/com/spring/staez/concert/model/dto/ConcertDTO.java
staez/src/main/java/com/spring/staez/concert/service/ConcertRestTemplate.java
staez/src/main/resources/mappers/concert-mapper.xml
staez/src/test/java/com/spring/staez/concert/model/dao/ConcertDaoTest.java
staez/src/test/java/com/spring/staez/concert/service/ConcertRestTemplateTest.java

[주재완] Fix: 공연 api 중복 저장 문제 수정 & 확인 필요

[주재완] Fix: 공연 api 중복 저장 문제 수정 & 확인 필요

---

staez/src/main/java/com/spring/staez/common/template/ScheduledTest.java
staez/src/main/java/com/spring/staez/concert/model/dao/ConcertDao.java
staez/src/main/java/com/spring/staez/concert/service/ConcertRestTemplate.java
staez/src/main/resources/mappers/concert-mapper.xml
staez/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
staez/src/test/java/com/spring/staez/concert/service/ConcertRestTemplateTest.java

[주재완] 남주님 조금만 더 힘내세요

---

staez/src/main/resources/mappers/concert-mapper.xml

[김남주] Fix : 콘서트 매퍼 오류 수정

---

staez/src/main/java/com/spring/staez/common/template/ConcertApiScheduled.java
staez/src/main/java/com/spring/staez/concert/controller/ConcertAPIController.java
staez/src/main/java/com/spring/staez/concert/model/dto/ConcertDto.java
staez/src/main/java/com/spring/staez/concert/service/ConcertRestTemplate.java
staez/src/main/resources/mappers/concert-mapper.xml
staez/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml

[김남주] Fix: 콘서트 mapper 수정

---

staez/src/main/java/com/spring/staez/aspect/LoggingAOP.java
staez/src/main/java/com/spring/staez/common/controller/CommonController.java
staez/src/main/java/com/spring/staez/common/model/dao/CommonDao.java
staez/src/main/java/com/spring/staez/common/template/ConcertApiScheduled.java
staez/src/main/java/com/spring/staez/concert/model/dao/ConcertDao.java
staez/src/main/java/com/spring/staez/concert/model/dto/ConcertDto.java
staez/src/main/java/com/spring/staez/concert/service/ConcertRestTemplate.java
staez/src/main/resources/mappers/community-mapper.xml
staez/src/main/resources/mappers/concert-mapper.xml
staez/src/main/webapp/resources/js/admin/concertInsertForm.js
staez/src/main/webapp/resources/js/admin/concertUpdateForm.js
staez/src/main/webapp/resources/js/api/adminapi.js
staez/src/main/webapp/resources/js/community/communityDetail.js
staez/src/main/webapp/resources/js/community/communityInsertForm.js
staez/src/main/webapp/resources/js/community/communityUpdateForm.js
staez/src/test/java/com/spring/staez/concert/controller/ConcertAPIControllerTest.java
staez/src/test/java/com/spring/staez/concert/model/dao/ConcertDaoTest.java
staez/src/test/java/com/spring/staez/concert/service/ConcertRestTemplateTest.java

API 로 호출한 concert, concert_attachment, concert_schedule DB에 넣기
미입력시 경고창
포스터 이미지 경로 수정

[주재완] 테스트 전 개발 사항

---

staez/src/main/java/com/spring/staez/concert/controller/ConcertAPIController.java
staez/src/main/webapp/resources/js/api/concertapi.js
staez/src/main/webapp/resources/js/concert/concertAPIDetailMain.js

[김남주]  Feat: 콘서트 api 세부페이지 구현 완료

[김남주]  Feat: 콘서트 api 세부페이지 구현 완료

---

staez/src/main/webapp/WEB-INF/views/concert/concertAPIDetailMain.jsp
staez/src/main/webapp/resources/css/concert/concertDetailMain.css
staez/src/main/webapp/resources/css/concert/concertMain.css
staez/src/main/webapp/resources/js/concert/concertAPIMain.js

[김남주]  Fix: trello 내용 수정

---

staez/src/main/java/com/spring/staez/user/controller/UserController.java
staez/src/main/java/com/spring/staez/user/model/dao/UserDao.java
staez/src/main/java/com/spring/staez/user/service/UserService.java
staez/src/main/java/com/spring/staez/user/service/UserServiceImpl.java
staez/src/main/resources/mappers/user-mapper.xml
staez/src/main/webapp/resources/js/api/userapi.js
staez/src/main/webapp/resources/js/user/findIdForm.js
staez/src/main/webapp/resources/js/user/findPwdForm.js

[장용준 ] Fix : 아아디찾기/ 비밀번호 찾기 다음버튼 버그 수정

[장용준 ] Fix : 아아디찾기/ 비밀번호 찾기 다음버튼 버그 수정

---

staez/src/main/webapp/resources/js/user/findIdForm.js
staez/src/main/webapp/resources/js/user/insertForm.js

[장용준] Docs : J쿼리문 JS로 바꿈

---

staez/src/main/webapp/resources/js/user/findIdForm.js
staez/src/main/webapp/resources/js/user/insertForm.js

[장용준] Fix : 회원가입시 핸드폰인증 안되는거 j쿼리떄문이라 그냥 JS로 바꿈

[장용준] Fix : 회원가입시 핸드폰인증 안되는거 j쿼리떄문이라 그냥 JS로 바꿈

---

staez/src/main/resources/mappers/concert-mapper.xml

[김남주]  Fix : 매퍼 오류수정

---

staez/src/main/webapp/WEB-INF/views/concert/concertMain.jsp
staez/src/main/webapp/resources/css/concert/concertMain.css
staez/src/main/webapp/resources/js/concert/concertAPIMain.js
staez/src/main/webapp/resources/js/concert/concertMain.js

[김남주]  Fix : 대중음악 오류수정

---

staez/src/main/webapp/WEB-INF/views/concert/concertMain.jsp
staez/src/main/webapp/resources/css/concert/concertMain.css
staez/src/main/webapp/resources/js/concert/concertAPIMain.js
staez/src/main/webapp/resources/js/concert/concertMain.js

[김남주]  Fix : 버튼 오류 수정
